### ISSUE TITLE
iOS: Enable "supervision mode" automatically

### ISSUE THREAD

**Issue by zner0L** [tweaselORG/appstraction#81]
In #44, I investigated how the "supervision mode" can be used to install root CAs without interaction. I'd like to implement this in appstraction as an internal iOS function. In order for that, we need to:

- Generate the `SupervisorHostCertificate`.
- Place the certificate in the `CloudConfigurationDetails.plist`
- Restart the device without having to re-jailbreak
- Save the private key somewhere save so we can use it to send configuration profiles

**Comment by baltpeter** [comment]
> Restart the device without having to re-jailbreak

Is that possible? :o

**Comment by zner0L** [comment]
I am thinking of trying https://github.com/digitalbazaar/forge, which is a native js implementation of TLS instead of the webcrypto API https://github.com/PeculiarVentures/PKI.js is relying on. I am not sure how much of a security trade of this really is, but since we are basically installing a backdoor on peoples devices, I guess we should at least secure it properly? Then again, PKCS#12 seems to be an extremely badly implemented standard, even in openSSL itself, and using  https://github.com/digitalbazaar/forge might be even better security.

**Comment by zner0L** [comment]
> Is that possible? :o

Yes. `ldrestart` restarts all the user space processes, but keeps the (jailbroken) kernel running.

**Comment by baltpeter** [comment]
On my iOS 15 device, `launchctl reboot userspace` seems to kill (and not restart) sshd.

If I just do `await ios._internal.userspaceRestart();`, the phone does restart but I get the following error:

```
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/home/benni/coding/JS/tweasel/appstraction/node_modules/ssh2/lib/client.js:745:12)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
```

I can only connect via SSH after I do "Launch Daemons" in the palera1n app.

**Comment by baltpeter** [comment]
That _doesn't_ happen with `ldrestart`.

**Comment by baltpeter** [comment]
Same thing on iOS 16. Here, the SSH session even stays intact with `ldrestart`.

**Comment by baltpeter** [comment]
So, if I enable the `supervision` capability and try to do:

```ts
await ios.ensureDevice();
await ios.installCertificateAuthority(caCertPath!);
```

On iOS 15, this fails:

```
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (/home/benni/coding/JS/tweasel/appstraction/node_modules/ssh2/lib/client.js:745:12)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  level: 'client-socket'
}
```

On iOS 16, it hangs.

**Comment by zner0L** [comment]
> On my iOS 15 device, `launchctl reboot userspace` seems to kill (and not restart) `sshd`.

I cannot reproduce this on either my iOS 15 or 16 devices. What version of palera1n are you using?

> Yes. ldrestart restarts all the user space processes, but keeps the (jailbroken) kernel running.

This is also not true. This only restarts the `LaunchDeamons`, but not `launchd`. So on iOS 15 `ldrestart` is enough to get the supervision mode activated, on iOS 16 this doesn’t work and needs `launchctl reboot userspace`.

**Comment by baltpeter** [comment]
> I am not using legacy anymore. Can you test jailbreaking with `palera1n-c`?

I've now wasted an hour trying to get that to work, [unsuccessfully](https://github.com/tweaselORG/meta/issues/4#issuecomment-1577102528). I don't know what else to try.
