### ISSUE TITLE
`resetDevice()` fails on Android

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/appstraction#96]
```
/home/benni/coding/JS/tweasel/appstraction/src/android.ts:330
            throw new Error(
                  ^


Error: You need to start the emulator.
    at Object.ensureDevice (/home/benni/coding/JS/tweasel/appstraction/src/android.ts:330:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.resetDevice (/home/benni/coding/JS/tweasel/appstraction/src/android.ts:321:9)
    at <anonymous> (/home/benni/coding/JS/tweasel/appstraction/examples/android-emulator.ts:25:5)
```

We are not waiting for the emulator in `ensureDevice()` anymore.

**Comment by baltpeter** [comment]
Same problem as https://github.com/tweaselORG/cli/issues/23.
